services:
  algasensors-rabbitmq:
    image: rabbitmq:3-management
    container_name: algasensors-rabbitmq
    ports:
      - "15672:15672"  # RabbitMQ management UI
      - "5672:5672"    # RabbitMQ AMQP protocol
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - algasensors-rabbitmq-data:/var/lib/rabbitmq
volumes:
  algasensors-rabbitmq-data:
    driver: local